name: windows_flutter
description: Flutter Windows 桌面应用
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  windows: true  # 只启用 Windows
